language: python
python:
  - 3.5
install:
  - pip install sphinx sphinx_rtd_theme sphinxcontrib.httpdomain sphinxcontrib.httpexample
script: make html
after_success:
  - ./push.sh
env:
  global:
    - secure: "PASTE ENCRYPTED RESULT HERE"
